version: '3.8'

services:
  
  mongodb:
    image: mongo:latest
    container_name: banco_de_dados
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

 
  backend:
    build: ./PROJETO-BACKEND
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      
      - NODE_ENV=development


  
  frontend:
    build: ./PROJETO-FRONTEND
    container_name: frontend
    ports:
      - "3000:55823"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend 


volumes:
  mongo_data: